// SPDX-FileCopyrightText: 2023 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus". DO NOT EDIT.

package model

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/seal-io/walrus/pkg/dao/model/internal"
	"github.com/seal-io/walrus/pkg/dao/model/predicate"
	"github.com/seal-io/walrus/pkg/dao/model/workflowsteptemplate"
)

// WorkflowStepTemplateDelete is the builder for deleting a WorkflowStepTemplate entity.
type WorkflowStepTemplateDelete struct {
	config
	hooks    []Hook
	mutation *WorkflowStepTemplateMutation
}

// Where appends a list predicates to the WorkflowStepTemplateDelete builder.
func (wstd *WorkflowStepTemplateDelete) Where(ps ...predicate.WorkflowStepTemplate) *WorkflowStepTemplateDelete {
	wstd.mutation.Where(ps...)
	return wstd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wstd *WorkflowStepTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wstd.sqlExec, wstd.mutation, wstd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wstd *WorkflowStepTemplateDelete) ExecX(ctx context.Context) int {
	n, err := wstd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wstd *WorkflowStepTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workflowsteptemplate.Table, sqlgraph.NewFieldSpec(workflowsteptemplate.FieldID, field.TypeString))
	_spec.Node.Schema = wstd.schemaConfig.WorkflowStepTemplate
	ctx = internal.NewSchemaConfigContext(ctx, wstd.schemaConfig)
	if ps := wstd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wstd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wstd.mutation.done = true
	return affected, err
}

// WorkflowStepTemplateDeleteOne is the builder for deleting a single WorkflowStepTemplate entity.
type WorkflowStepTemplateDeleteOne struct {
	wstd *WorkflowStepTemplateDelete
}

// Where appends a list predicates to the WorkflowStepTemplateDelete builder.
func (wstdo *WorkflowStepTemplateDeleteOne) Where(ps ...predicate.WorkflowStepTemplate) *WorkflowStepTemplateDeleteOne {
	wstdo.wstd.mutation.Where(ps...)
	return wstdo
}

// Exec executes the deletion query.
func (wstdo *WorkflowStepTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := wstdo.wstd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workflowsteptemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wstdo *WorkflowStepTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := wstdo.Exec(ctx); err != nil {
		panic(err)
	}
}
