// SPDX-FileCopyrightText: 2023 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus". DO NOT EDIT.

package model

import (
	"context"
	stdsql "database/sql"
	"errors"
	"fmt"
	"reflect"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"

	"github.com/seal-io/walrus/pkg/dao/model/internal"
	"github.com/seal-io/walrus/pkg/dao/model/predicate"
	"github.com/seal-io/walrus/pkg/dao/model/workflowstep"
	"github.com/seal-io/walrus/pkg/dao/model/workflowstepexecution"
	"github.com/seal-io/walrus/pkg/dao/types"
	"github.com/seal-io/walrus/pkg/dao/types/object"
)

// WorkflowStepUpdate is the builder for updating WorkflowStep entities.
type WorkflowStepUpdate struct {
	config
	hooks     []Hook
	mutation  *WorkflowStepMutation
	modifiers []func(*sql.UpdateBuilder)
	object    *WorkflowStep
}

// Where appends a list predicates to the WorkflowStepUpdate builder.
func (wsu *WorkflowStepUpdate) Where(ps ...predicate.WorkflowStep) *WorkflowStepUpdate {
	wsu.mutation.Where(ps...)
	return wsu
}

// SetDescription sets the "description" field.
func (wsu *WorkflowStepUpdate) SetDescription(s string) *WorkflowStepUpdate {
	wsu.mutation.SetDescription(s)
	return wsu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wsu *WorkflowStepUpdate) SetNillableDescription(s *string) *WorkflowStepUpdate {
	if s != nil {
		wsu.SetDescription(*s)
	}
	return wsu
}

// ClearDescription clears the value of the "description" field.
func (wsu *WorkflowStepUpdate) ClearDescription() *WorkflowStepUpdate {
	wsu.mutation.ClearDescription()
	return wsu
}

// SetLabels sets the "labels" field.
func (wsu *WorkflowStepUpdate) SetLabels(m map[string]string) *WorkflowStepUpdate {
	wsu.mutation.SetLabels(m)
	return wsu
}

// ClearLabels clears the value of the "labels" field.
func (wsu *WorkflowStepUpdate) ClearLabels() *WorkflowStepUpdate {
	wsu.mutation.ClearLabels()
	return wsu
}

// SetAnnotations sets the "annotations" field.
func (wsu *WorkflowStepUpdate) SetAnnotations(m map[string]string) *WorkflowStepUpdate {
	wsu.mutation.SetAnnotations(m)
	return wsu
}

// ClearAnnotations clears the value of the "annotations" field.
func (wsu *WorkflowStepUpdate) ClearAnnotations() *WorkflowStepUpdate {
	wsu.mutation.ClearAnnotations()
	return wsu
}

// SetUpdateTime sets the "update_time" field.
func (wsu *WorkflowStepUpdate) SetUpdateTime(t time.Time) *WorkflowStepUpdate {
	wsu.mutation.SetUpdateTime(t)
	return wsu
}

// SetSpec sets the "spec" field.
func (wsu *WorkflowStepUpdate) SetSpec(m map[string]interface{}) *WorkflowStepUpdate {
	wsu.mutation.SetSpec(m)
	return wsu
}

// ClearSpec clears the value of the "spec" field.
func (wsu *WorkflowStepUpdate) ClearSpec() *WorkflowStepUpdate {
	wsu.mutation.ClearSpec()
	return wsu
}

// SetInput sets the "input" field.
func (wsu *WorkflowStepUpdate) SetInput(m map[string]interface{}) *WorkflowStepUpdate {
	wsu.mutation.SetInput(m)
	return wsu
}

// ClearInput clears the value of the "input" field.
func (wsu *WorkflowStepUpdate) ClearInput() *WorkflowStepUpdate {
	wsu.mutation.ClearInput()
	return wsu
}

// SetOutput sets the "output" field.
func (wsu *WorkflowStepUpdate) SetOutput(m map[string]interface{}) *WorkflowStepUpdate {
	wsu.mutation.SetOutput(m)
	return wsu
}

// ClearOutput clears the value of the "output" field.
func (wsu *WorkflowStepUpdate) ClearOutput() *WorkflowStepUpdate {
	wsu.mutation.ClearOutput()
	return wsu
}

// SetDependencies sets the "dependencies" field.
func (wsu *WorkflowStepUpdate) SetDependencies(o []object.ID) *WorkflowStepUpdate {
	wsu.mutation.SetDependencies(o)
	return wsu
}

// AppendDependencies appends o to the "dependencies" field.
func (wsu *WorkflowStepUpdate) AppendDependencies(o []object.ID) *WorkflowStepUpdate {
	wsu.mutation.AppendDependencies(o)
	return wsu
}

// SetRetryStrategy sets the "retryStrategy" field.
func (wsu *WorkflowStepUpdate) SetRetryStrategy(ts types.RetryStrategy) *WorkflowStepUpdate {
	wsu.mutation.SetRetryStrategy(ts)
	return wsu
}

// ClearRetryStrategy clears the value of the "retryStrategy" field.
func (wsu *WorkflowStepUpdate) ClearRetryStrategy() *WorkflowStepUpdate {
	wsu.mutation.ClearRetryStrategy()
	return wsu
}

// SetTimeout sets the "timeout" field.
func (wsu *WorkflowStepUpdate) SetTimeout(i int) *WorkflowStepUpdate {
	wsu.mutation.ResetTimeout()
	wsu.mutation.SetTimeout(i)
	return wsu
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (wsu *WorkflowStepUpdate) SetNillableTimeout(i *int) *WorkflowStepUpdate {
	if i != nil {
		wsu.SetTimeout(*i)
	}
	return wsu
}

// AddTimeout adds i to the "timeout" field.
func (wsu *WorkflowStepUpdate) AddTimeout(i int) *WorkflowStepUpdate {
	wsu.mutation.AddTimeout(i)
	return wsu
}

// AddExecutionIDs adds the "executions" edge to the WorkflowStepExecution entity by IDs.
func (wsu *WorkflowStepUpdate) AddExecutionIDs(ids ...object.ID) *WorkflowStepUpdate {
	wsu.mutation.AddExecutionIDs(ids...)
	return wsu
}

// AddExecutions adds the "executions" edges to the WorkflowStepExecution entity.
func (wsu *WorkflowStepUpdate) AddExecutions(w ...*WorkflowStepExecution) *WorkflowStepUpdate {
	ids := make([]object.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsu.AddExecutionIDs(ids...)
}

// Mutation returns the WorkflowStepMutation object of the builder.
func (wsu *WorkflowStepUpdate) Mutation() *WorkflowStepMutation {
	return wsu.mutation
}

// ClearExecutions clears all "executions" edges to the WorkflowStepExecution entity.
func (wsu *WorkflowStepUpdate) ClearExecutions() *WorkflowStepUpdate {
	wsu.mutation.ClearExecutions()
	return wsu
}

// RemoveExecutionIDs removes the "executions" edge to WorkflowStepExecution entities by IDs.
func (wsu *WorkflowStepUpdate) RemoveExecutionIDs(ids ...object.ID) *WorkflowStepUpdate {
	wsu.mutation.RemoveExecutionIDs(ids...)
	return wsu
}

// RemoveExecutions removes "executions" edges to WorkflowStepExecution entities.
func (wsu *WorkflowStepUpdate) RemoveExecutions(w ...*WorkflowStepExecution) *WorkflowStepUpdate {
	ids := make([]object.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsu.RemoveExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wsu *WorkflowStepUpdate) Save(ctx context.Context) (int, error) {
	if err := wsu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, wsu.sqlSave, wsu.mutation, wsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsu *WorkflowStepUpdate) SaveX(ctx context.Context) int {
	affected, err := wsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wsu *WorkflowStepUpdate) Exec(ctx context.Context) error {
	_, err := wsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsu *WorkflowStepUpdate) ExecX(ctx context.Context) {
	if err := wsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wsu *WorkflowStepUpdate) defaults() error {
	if _, ok := wsu.mutation.UpdateTime(); !ok {
		if workflowstep.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("model: uninitialized workflowstep.UpdateDefaultUpdateTime (forgotten import model/runtime?)")
		}
		v := workflowstep.UpdateDefaultUpdateTime()
		wsu.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (wsu *WorkflowStepUpdate) check() error {
	if v, ok := wsu.mutation.Timeout(); ok {
		if err := workflowstep.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf(`model: validator failed for field "WorkflowStep.timeout": %w`, err)}
		}
	}
	if _, ok := wsu.mutation.ProjectID(); wsu.mutation.ProjectCleared() && !ok {
		return errors.New(`model: clearing a required unique edge "WorkflowStep.project"`)
	}
	if _, ok := wsu.mutation.StageID(); wsu.mutation.StageCleared() && !ok {
		return errors.New(`model: clearing a required unique edge "WorkflowStep.stage"`)
	}
	return nil
}

// Set is different from other Set* methods,
// it sets the value by judging the definition of each field within the entire object.
//
// For default fields, Set calls if the value is not zero.
//
// For no default but required fields, Set calls directly.
//
// For no default but optional fields, Set calls if the value is not zero,
// or clears if the value is zero.
//
// For example:
//
//	## Without Default
//
//	### Required
//
//	db.SetX(obj.X)
//
//	### Optional or Default
//
//	if _is_zero_value_(obj.X) {
//	   db.SetX(obj.X)
//	} else {
//	   db.ClearX()
//	}
//
//	## With Default
//
//	if _is_zero_value_(obj.X) {
//	   db.SetX(obj.X)
//	}
func (wsu *WorkflowStepUpdate) Set(obj *WorkflowStep) *WorkflowStepUpdate {
	// Without Default.
	if obj.Description != "" {
		wsu.SetDescription(obj.Description)
	} else {
		wsu.ClearDescription()
	}
	if !reflect.ValueOf(obj.Labels).IsZero() {
		wsu.SetLabels(obj.Labels)
	} else {
		wsu.ClearLabels()
	}
	if !reflect.ValueOf(obj.Annotations).IsZero() {
		wsu.SetAnnotations(obj.Annotations)
	}
	if !reflect.ValueOf(obj.Spec).IsZero() {
		wsu.SetSpec(obj.Spec)
	} else {
		wsu.ClearSpec()
	}
	if !reflect.ValueOf(obj.Input).IsZero() {
		wsu.SetInput(obj.Input)
	} else {
		wsu.ClearInput()
	}
	if !reflect.ValueOf(obj.Output).IsZero() {
		wsu.SetOutput(obj.Output)
	} else {
		wsu.ClearOutput()
	}
	wsu.SetDependencies(obj.Dependencies)
	if !reflect.ValueOf(obj.RetryStrategy).IsZero() {
		wsu.SetRetryStrategy(obj.RetryStrategy)
	} else {
		wsu.ClearRetryStrategy()
	}
	wsu.SetTimeout(obj.Timeout)

	// With Default.
	if obj.UpdateTime != nil {
		wsu.SetUpdateTime(*obj.UpdateTime)
	}

	// Record the given object.
	wsu.object = obj

	return wsu
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wsu *WorkflowStepUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowStepUpdate {
	wsu.modifiers = append(wsu.modifiers, modifiers...)
	return wsu
}

func (wsu *WorkflowStepUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowstep.Table, workflowstep.Columns, sqlgraph.NewFieldSpec(workflowstep.FieldID, field.TypeString))
	if ps := wsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsu.mutation.Description(); ok {
		_spec.SetField(workflowstep.FieldDescription, field.TypeString, value)
	}
	if wsu.mutation.DescriptionCleared() {
		_spec.ClearField(workflowstep.FieldDescription, field.TypeString)
	}
	if value, ok := wsu.mutation.Labels(); ok {
		_spec.SetField(workflowstep.FieldLabels, field.TypeJSON, value)
	}
	if wsu.mutation.LabelsCleared() {
		_spec.ClearField(workflowstep.FieldLabels, field.TypeJSON)
	}
	if value, ok := wsu.mutation.Annotations(); ok {
		_spec.SetField(workflowstep.FieldAnnotations, field.TypeJSON, value)
	}
	if wsu.mutation.AnnotationsCleared() {
		_spec.ClearField(workflowstep.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := wsu.mutation.UpdateTime(); ok {
		_spec.SetField(workflowstep.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wsu.mutation.Spec(); ok {
		_spec.SetField(workflowstep.FieldSpec, field.TypeJSON, value)
	}
	if wsu.mutation.SpecCleared() {
		_spec.ClearField(workflowstep.FieldSpec, field.TypeJSON)
	}
	if value, ok := wsu.mutation.Input(); ok {
		_spec.SetField(workflowstep.FieldInput, field.TypeJSON, value)
	}
	if wsu.mutation.InputCleared() {
		_spec.ClearField(workflowstep.FieldInput, field.TypeJSON)
	}
	if value, ok := wsu.mutation.Output(); ok {
		_spec.SetField(workflowstep.FieldOutput, field.TypeJSON, value)
	}
	if wsu.mutation.OutputCleared() {
		_spec.ClearField(workflowstep.FieldOutput, field.TypeJSON)
	}
	if value, ok := wsu.mutation.Dependencies(); ok {
		_spec.SetField(workflowstep.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := wsu.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflowstep.FieldDependencies, value)
		})
	}
	if value, ok := wsu.mutation.RetryStrategy(); ok {
		_spec.SetField(workflowstep.FieldRetryStrategy, field.TypeJSON, value)
	}
	if wsu.mutation.RetryStrategyCleared() {
		_spec.ClearField(workflowstep.FieldRetryStrategy, field.TypeJSON)
	}
	if value, ok := wsu.mutation.Timeout(); ok {
		_spec.SetField(workflowstep.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := wsu.mutation.AddedTimeout(); ok {
		_spec.AddField(workflowstep.FieldTimeout, field.TypeInt, value)
	}
	if wsu.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsu.schemaConfig.WorkflowStepExecution
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsu.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !wsu.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsu.schemaConfig.WorkflowStepExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsu.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsu.schemaConfig.WorkflowStepExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = wsu.schemaConfig.WorkflowStep
	ctx = internal.NewSchemaConfigContext(ctx, wsu.schemaConfig)
	_spec.AddModifiers(wsu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, wsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wsu.mutation.done = true
	return n, nil
}

// WorkflowStepUpdateOne is the builder for updating a single WorkflowStep entity.
type WorkflowStepUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *WorkflowStepMutation
	modifiers []func(*sql.UpdateBuilder)
	object    *WorkflowStep
}

// SetDescription sets the "description" field.
func (wsuo *WorkflowStepUpdateOne) SetDescription(s string) *WorkflowStepUpdateOne {
	wsuo.mutation.SetDescription(s)
	return wsuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wsuo *WorkflowStepUpdateOne) SetNillableDescription(s *string) *WorkflowStepUpdateOne {
	if s != nil {
		wsuo.SetDescription(*s)
	}
	return wsuo
}

// ClearDescription clears the value of the "description" field.
func (wsuo *WorkflowStepUpdateOne) ClearDescription() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearDescription()
	return wsuo
}

// SetLabels sets the "labels" field.
func (wsuo *WorkflowStepUpdateOne) SetLabels(m map[string]string) *WorkflowStepUpdateOne {
	wsuo.mutation.SetLabels(m)
	return wsuo
}

// ClearLabels clears the value of the "labels" field.
func (wsuo *WorkflowStepUpdateOne) ClearLabels() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearLabels()
	return wsuo
}

// SetAnnotations sets the "annotations" field.
func (wsuo *WorkflowStepUpdateOne) SetAnnotations(m map[string]string) *WorkflowStepUpdateOne {
	wsuo.mutation.SetAnnotations(m)
	return wsuo
}

// ClearAnnotations clears the value of the "annotations" field.
func (wsuo *WorkflowStepUpdateOne) ClearAnnotations() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearAnnotations()
	return wsuo
}

// SetUpdateTime sets the "update_time" field.
func (wsuo *WorkflowStepUpdateOne) SetUpdateTime(t time.Time) *WorkflowStepUpdateOne {
	wsuo.mutation.SetUpdateTime(t)
	return wsuo
}

// SetSpec sets the "spec" field.
func (wsuo *WorkflowStepUpdateOne) SetSpec(m map[string]interface{}) *WorkflowStepUpdateOne {
	wsuo.mutation.SetSpec(m)
	return wsuo
}

// ClearSpec clears the value of the "spec" field.
func (wsuo *WorkflowStepUpdateOne) ClearSpec() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearSpec()
	return wsuo
}

// SetInput sets the "input" field.
func (wsuo *WorkflowStepUpdateOne) SetInput(m map[string]interface{}) *WorkflowStepUpdateOne {
	wsuo.mutation.SetInput(m)
	return wsuo
}

// ClearInput clears the value of the "input" field.
func (wsuo *WorkflowStepUpdateOne) ClearInput() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearInput()
	return wsuo
}

// SetOutput sets the "output" field.
func (wsuo *WorkflowStepUpdateOne) SetOutput(m map[string]interface{}) *WorkflowStepUpdateOne {
	wsuo.mutation.SetOutput(m)
	return wsuo
}

// ClearOutput clears the value of the "output" field.
func (wsuo *WorkflowStepUpdateOne) ClearOutput() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearOutput()
	return wsuo
}

// SetDependencies sets the "dependencies" field.
func (wsuo *WorkflowStepUpdateOne) SetDependencies(o []object.ID) *WorkflowStepUpdateOne {
	wsuo.mutation.SetDependencies(o)
	return wsuo
}

// AppendDependencies appends o to the "dependencies" field.
func (wsuo *WorkflowStepUpdateOne) AppendDependencies(o []object.ID) *WorkflowStepUpdateOne {
	wsuo.mutation.AppendDependencies(o)
	return wsuo
}

// SetRetryStrategy sets the "retryStrategy" field.
func (wsuo *WorkflowStepUpdateOne) SetRetryStrategy(ts types.RetryStrategy) *WorkflowStepUpdateOne {
	wsuo.mutation.SetRetryStrategy(ts)
	return wsuo
}

// ClearRetryStrategy clears the value of the "retryStrategy" field.
func (wsuo *WorkflowStepUpdateOne) ClearRetryStrategy() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearRetryStrategy()
	return wsuo
}

// SetTimeout sets the "timeout" field.
func (wsuo *WorkflowStepUpdateOne) SetTimeout(i int) *WorkflowStepUpdateOne {
	wsuo.mutation.ResetTimeout()
	wsuo.mutation.SetTimeout(i)
	return wsuo
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (wsuo *WorkflowStepUpdateOne) SetNillableTimeout(i *int) *WorkflowStepUpdateOne {
	if i != nil {
		wsuo.SetTimeout(*i)
	}
	return wsuo
}

// AddTimeout adds i to the "timeout" field.
func (wsuo *WorkflowStepUpdateOne) AddTimeout(i int) *WorkflowStepUpdateOne {
	wsuo.mutation.AddTimeout(i)
	return wsuo
}

// AddExecutionIDs adds the "executions" edge to the WorkflowStepExecution entity by IDs.
func (wsuo *WorkflowStepUpdateOne) AddExecutionIDs(ids ...object.ID) *WorkflowStepUpdateOne {
	wsuo.mutation.AddExecutionIDs(ids...)
	return wsuo
}

// AddExecutions adds the "executions" edges to the WorkflowStepExecution entity.
func (wsuo *WorkflowStepUpdateOne) AddExecutions(w ...*WorkflowStepExecution) *WorkflowStepUpdateOne {
	ids := make([]object.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsuo.AddExecutionIDs(ids...)
}

// Mutation returns the WorkflowStepMutation object of the builder.
func (wsuo *WorkflowStepUpdateOne) Mutation() *WorkflowStepMutation {
	return wsuo.mutation
}

// ClearExecutions clears all "executions" edges to the WorkflowStepExecution entity.
func (wsuo *WorkflowStepUpdateOne) ClearExecutions() *WorkflowStepUpdateOne {
	wsuo.mutation.ClearExecutions()
	return wsuo
}

// RemoveExecutionIDs removes the "executions" edge to WorkflowStepExecution entities by IDs.
func (wsuo *WorkflowStepUpdateOne) RemoveExecutionIDs(ids ...object.ID) *WorkflowStepUpdateOne {
	wsuo.mutation.RemoveExecutionIDs(ids...)
	return wsuo
}

// RemoveExecutions removes "executions" edges to WorkflowStepExecution entities.
func (wsuo *WorkflowStepUpdateOne) RemoveExecutions(w ...*WorkflowStepExecution) *WorkflowStepUpdateOne {
	ids := make([]object.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wsuo.RemoveExecutionIDs(ids...)
}

// Where appends a list predicates to the WorkflowStepUpdate builder.
func (wsuo *WorkflowStepUpdateOne) Where(ps ...predicate.WorkflowStep) *WorkflowStepUpdateOne {
	wsuo.mutation.Where(ps...)
	return wsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wsuo *WorkflowStepUpdateOne) Select(field string, fields ...string) *WorkflowStepUpdateOne {
	wsuo.fields = append([]string{field}, fields...)
	return wsuo
}

// Save executes the query and returns the updated WorkflowStep entity.
func (wsuo *WorkflowStepUpdateOne) Save(ctx context.Context) (*WorkflowStep, error) {
	if err := wsuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, wsuo.sqlSave, wsuo.mutation, wsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wsuo *WorkflowStepUpdateOne) SaveX(ctx context.Context) *WorkflowStep {
	node, err := wsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wsuo *WorkflowStepUpdateOne) Exec(ctx context.Context) error {
	_, err := wsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsuo *WorkflowStepUpdateOne) ExecX(ctx context.Context) {
	if err := wsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wsuo *WorkflowStepUpdateOne) defaults() error {
	if _, ok := wsuo.mutation.UpdateTime(); !ok {
		if workflowstep.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("model: uninitialized workflowstep.UpdateDefaultUpdateTime (forgotten import model/runtime?)")
		}
		v := workflowstep.UpdateDefaultUpdateTime()
		wsuo.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (wsuo *WorkflowStepUpdateOne) check() error {
	if v, ok := wsuo.mutation.Timeout(); ok {
		if err := workflowstep.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf(`model: validator failed for field "WorkflowStep.timeout": %w`, err)}
		}
	}
	if _, ok := wsuo.mutation.ProjectID(); wsuo.mutation.ProjectCleared() && !ok {
		return errors.New(`model: clearing a required unique edge "WorkflowStep.project"`)
	}
	if _, ok := wsuo.mutation.StageID(); wsuo.mutation.StageCleared() && !ok {
		return errors.New(`model: clearing a required unique edge "WorkflowStep.stage"`)
	}
	return nil
}

// Set is different from other Set* methods,
// it sets the value by judging the definition of each field within the entire object.
//
// For default fields, Set calls if the value changes from the original.
//
// For no default but required fields, Set calls if the value changes from the original.
//
// For no default but optional fields, Set calls if the value changes from the original,
// or clears if changes to zero.
//
// For example:
//
//	## Without Default
//
//	### Required
//
//	db.SetX(obj.X)
//
//	### Optional or Default
//
//	if _is_zero_value_(obj.X) {
//	   if _is_not_equal_(db.X, obj.X) {
//	      db.SetX(obj.X)
//	   }
//	} else {
//	   db.ClearX()
//	}
//
//	## With Default
//
//	if _is_zero_value_(obj.X) && _is_not_equal_(db.X, obj.X) {
//	   db.SetX(obj.X)
//	}
func (wsuo *WorkflowStepUpdateOne) Set(obj *WorkflowStep) *WorkflowStepUpdateOne {
	h := func(n ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			mt := m.(*WorkflowStepMutation)
			db, err := mt.Client().WorkflowStep.Get(ctx, *mt.id)
			if err != nil {
				return nil, fmt.Errorf("failed getting WorkflowStep with id: %v", *mt.id)
			}

			// Without Default.
			if obj.Description != "" {
				if db.Description != obj.Description {
					wsuo.SetDescription(obj.Description)
				}
			} else {
				wsuo.ClearDescription()
			}
			if !reflect.ValueOf(obj.Labels).IsZero() {
				if !reflect.DeepEqual(db.Labels, obj.Labels) {
					wsuo.SetLabels(obj.Labels)
				}
			} else {
				wsuo.ClearLabels()
			}
			if !reflect.ValueOf(obj.Annotations).IsZero() {
				if !reflect.DeepEqual(db.Annotations, obj.Annotations) {
					wsuo.SetAnnotations(obj.Annotations)
				}
			}
			if !reflect.ValueOf(obj.Spec).IsZero() {
				if !reflect.DeepEqual(db.Spec, obj.Spec) {
					wsuo.SetSpec(obj.Spec)
				}
			} else {
				wsuo.ClearSpec()
			}
			if !reflect.ValueOf(obj.Input).IsZero() {
				if !reflect.DeepEqual(db.Input, obj.Input) {
					wsuo.SetInput(obj.Input)
				}
			} else {
				wsuo.ClearInput()
			}
			if !reflect.ValueOf(obj.Output).IsZero() {
				if !reflect.DeepEqual(db.Output, obj.Output) {
					wsuo.SetOutput(obj.Output)
				}
			} else {
				wsuo.ClearOutput()
			}
			if !reflect.DeepEqual(db.Dependencies, obj.Dependencies) {
				wsuo.SetDependencies(obj.Dependencies)
			}
			if !reflect.ValueOf(obj.RetryStrategy).IsZero() {
				if !reflect.DeepEqual(db.RetryStrategy, obj.RetryStrategy) {
					wsuo.SetRetryStrategy(obj.RetryStrategy)
				}
			} else {
				wsuo.ClearRetryStrategy()
			}
			if db.Timeout != obj.Timeout {
				wsuo.SetTimeout(obj.Timeout)
			}

			// With Default.
			if (obj.UpdateTime != nil) && (!reflect.DeepEqual(db.UpdateTime, obj.UpdateTime)) {
				wsuo.SetUpdateTime(*obj.UpdateTime)
			}

			// Record the given object.
			wsuo.object = obj

			return n.Mutate(ctx, m)
		})
	}

	wsuo.hooks = append(wsuo.hooks, h)

	return wsuo
}

// getClientSet returns the ClientSet for the given builder.
func (wsuo *WorkflowStepUpdateOne) getClientSet() (mc ClientSet) {
	if _, ok := wsuo.config.driver.(*txDriver); ok {
		tx := &Tx{config: wsuo.config}
		tx.init()
		mc = tx
	} else {
		cli := &Client{config: wsuo.config}
		cli.init()
		mc = cli
	}
	return mc
}

// SaveE calls the given function after updated the WorkflowStep entity,
// which is always good for cascading update operations.
func (wsuo *WorkflowStepUpdateOne) SaveE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowStep) error) (*WorkflowStep, error) {
	obj, err := wsuo.Save(ctx)
	if err != nil &&
		(wsuo.object == nil || !errors.Is(err, stdsql.ErrNoRows)) {
		return nil, err
	}

	if len(cbs) == 0 {
		return obj, err
	}

	mc := wsuo.getClientSet()

	if obj == nil {
		obj = wsuo.object
	} else if x := wsuo.object; x != nil {
		if _, set := wsuo.mutation.Field(workflowstep.FieldDescription); set {
			obj.Description = x.Description
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldLabels); set {
			obj.Labels = x.Labels
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldAnnotations); set {
			obj.Annotations = x.Annotations
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldSpec); set {
			obj.Spec = x.Spec
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldInput); set {
			obj.Input = x.Input
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldOutput); set {
			obj.Output = x.Output
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldDependencies); set {
			obj.Dependencies = x.Dependencies
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldRetryStrategy); set {
			obj.RetryStrategy = x.RetryStrategy
		}
		if _, set := wsuo.mutation.Field(workflowstep.FieldTimeout); set {
			obj.Timeout = x.Timeout
		}
		obj.Edges = x.Edges
	}

	for i := range cbs {
		if err = cbs[i](ctx, mc, obj); err != nil {
			return nil, err
		}
	}

	return obj, nil
}

// SaveEX is like SaveE, but panics if an error occurs.
func (wsuo *WorkflowStepUpdateOne) SaveEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowStep) error) *WorkflowStep {
	obj, err := wsuo.SaveE(ctx, cbs...)
	if err != nil {
		panic(err)
	}
	return obj
}

// ExecE calls the given function after executed the query,
// which is always good for cascading update operations.
func (wsuo *WorkflowStepUpdateOne) ExecE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowStep) error) error {
	_, err := wsuo.SaveE(ctx, cbs...)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wsuo *WorkflowStepUpdateOne) ExecEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowStep) error) {
	if err := wsuo.ExecE(ctx, cbs...); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (wsuo *WorkflowStepUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *WorkflowStepUpdateOne {
	wsuo.modifiers = append(wsuo.modifiers, modifiers...)
	return wsuo
}

func (wsuo *WorkflowStepUpdateOne) sqlSave(ctx context.Context) (_node *WorkflowStep, err error) {
	if err := wsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workflowstep.Table, workflowstep.Columns, sqlgraph.NewFieldSpec(workflowstep.FieldID, field.TypeString))
	id, ok := wsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`model: missing "WorkflowStep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workflowstep.FieldID)
		for _, f := range fields {
			if !workflowstep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
			}
			if f != workflowstep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wsuo.mutation.Description(); ok {
		_spec.SetField(workflowstep.FieldDescription, field.TypeString, value)
	}
	if wsuo.mutation.DescriptionCleared() {
		_spec.ClearField(workflowstep.FieldDescription, field.TypeString)
	}
	if value, ok := wsuo.mutation.Labels(); ok {
		_spec.SetField(workflowstep.FieldLabels, field.TypeJSON, value)
	}
	if wsuo.mutation.LabelsCleared() {
		_spec.ClearField(workflowstep.FieldLabels, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.Annotations(); ok {
		_spec.SetField(workflowstep.FieldAnnotations, field.TypeJSON, value)
	}
	if wsuo.mutation.AnnotationsCleared() {
		_spec.ClearField(workflowstep.FieldAnnotations, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.UpdateTime(); ok {
		_spec.SetField(workflowstep.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := wsuo.mutation.Spec(); ok {
		_spec.SetField(workflowstep.FieldSpec, field.TypeJSON, value)
	}
	if wsuo.mutation.SpecCleared() {
		_spec.ClearField(workflowstep.FieldSpec, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.Input(); ok {
		_spec.SetField(workflowstep.FieldInput, field.TypeJSON, value)
	}
	if wsuo.mutation.InputCleared() {
		_spec.ClearField(workflowstep.FieldInput, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.Output(); ok {
		_spec.SetField(workflowstep.FieldOutput, field.TypeJSON, value)
	}
	if wsuo.mutation.OutputCleared() {
		_spec.ClearField(workflowstep.FieldOutput, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.Dependencies(); ok {
		_spec.SetField(workflowstep.FieldDependencies, field.TypeJSON, value)
	}
	if value, ok := wsuo.mutation.AppendedDependencies(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, workflowstep.FieldDependencies, value)
		})
	}
	if value, ok := wsuo.mutation.RetryStrategy(); ok {
		_spec.SetField(workflowstep.FieldRetryStrategy, field.TypeJSON, value)
	}
	if wsuo.mutation.RetryStrategyCleared() {
		_spec.ClearField(workflowstep.FieldRetryStrategy, field.TypeJSON)
	}
	if value, ok := wsuo.mutation.Timeout(); ok {
		_spec.SetField(workflowstep.FieldTimeout, field.TypeInt, value)
	}
	if value, ok := wsuo.mutation.AddedTimeout(); ok {
		_spec.AddField(workflowstep.FieldTimeout, field.TypeInt, value)
	}
	if wsuo.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsuo.schemaConfig.WorkflowStepExecution
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsuo.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !wsuo.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsuo.schemaConfig.WorkflowStepExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wsuo.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowstep.ExecutionsTable,
			Columns: []string{workflowstep.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstepexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wsuo.schemaConfig.WorkflowStepExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.Node.Schema = wsuo.schemaConfig.WorkflowStep
	ctx = internal.NewSchemaConfigContext(ctx, wsuo.schemaConfig)
	_spec.AddModifiers(wsuo.modifiers...)
	_node = &WorkflowStep{config: wsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workflowstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wsuo.mutation.done = true
	return _node, nil
}
