// SPDX-FileCopyrightText: 2023 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus". DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/seal-io/walrus/pkg/dao/model/project"
	"github.com/seal-io/walrus/pkg/dao/model/workflow"
	"github.com/seal-io/walrus/pkg/dao/model/workflowexecution"
	"github.com/seal-io/walrus/pkg/dao/model/workflowstageexecution"
	"github.com/seal-io/walrus/pkg/dao/types/object"
	"github.com/seal-io/walrus/pkg/dao/types/status"
)

// WorkflowExecutionCreate is the builder for creating a WorkflowExecution entity.
type WorkflowExecutionCreate struct {
	config
	mutation   *WorkflowExecutionMutation
	hooks      []Hook
	conflict   []sql.ConflictOption
	object     *WorkflowExecution
	fromUpsert bool
}

// SetName sets the "name" field.
func (wec *WorkflowExecutionCreate) SetName(s string) *WorkflowExecutionCreate {
	wec.mutation.SetName(s)
	return wec
}

// SetDescription sets the "description" field.
func (wec *WorkflowExecutionCreate) SetDescription(s string) *WorkflowExecutionCreate {
	wec.mutation.SetDescription(s)
	return wec
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableDescription(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetDescription(*s)
	}
	return wec
}

// SetLabels sets the "labels" field.
func (wec *WorkflowExecutionCreate) SetLabels(m map[string]string) *WorkflowExecutionCreate {
	wec.mutation.SetLabels(m)
	return wec
}

// SetAnnotations sets the "annotations" field.
func (wec *WorkflowExecutionCreate) SetAnnotations(m map[string]string) *WorkflowExecutionCreate {
	wec.mutation.SetAnnotations(m)
	return wec
}

// SetCreateTime sets the "create_time" field.
func (wec *WorkflowExecutionCreate) SetCreateTime(t time.Time) *WorkflowExecutionCreate {
	wec.mutation.SetCreateTime(t)
	return wec
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableCreateTime(t *time.Time) *WorkflowExecutionCreate {
	if t != nil {
		wec.SetCreateTime(*t)
	}
	return wec
}

// SetUpdateTime sets the "update_time" field.
func (wec *WorkflowExecutionCreate) SetUpdateTime(t time.Time) *WorkflowExecutionCreate {
	wec.mutation.SetUpdateTime(t)
	return wec
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableUpdateTime(t *time.Time) *WorkflowExecutionCreate {
	if t != nil {
		wec.SetUpdateTime(*t)
	}
	return wec
}

// SetStatus sets the "status" field.
func (wec *WorkflowExecutionCreate) SetStatus(s status.Status) *WorkflowExecutionCreate {
	wec.mutation.SetStatus(s)
	return wec
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableStatus(s *status.Status) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetStatus(*s)
	}
	return wec
}

// SetProjectID sets the "project_id" field.
func (wec *WorkflowExecutionCreate) SetProjectID(o object.ID) *WorkflowExecutionCreate {
	wec.mutation.SetProjectID(o)
	return wec
}

// SetWorkflowID sets the "workflow_id" field.
func (wec *WorkflowExecutionCreate) SetWorkflowID(o object.ID) *WorkflowExecutionCreate {
	wec.mutation.SetWorkflowID(o)
	return wec
}

// SetSubjectID sets the "subject_id" field.
func (wec *WorkflowExecutionCreate) SetSubjectID(o object.ID) *WorkflowExecutionCreate {
	wec.mutation.SetSubjectID(o)
	return wec
}

// SetProgress sets the "progress" field.
func (wec *WorkflowExecutionCreate) SetProgress(s string) *WorkflowExecutionCreate {
	wec.mutation.SetProgress(s)
	return wec
}

// SetDuration sets the "duration" field.
func (wec *WorkflowExecutionCreate) SetDuration(i int) *WorkflowExecutionCreate {
	wec.mutation.SetDuration(i)
	return wec
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableDuration(i *int) *WorkflowExecutionCreate {
	if i != nil {
		wec.SetDuration(*i)
	}
	return wec
}

// SetStageExecutionIds sets the "stage_execution_ids" field.
func (wec *WorkflowExecutionCreate) SetStageExecutionIds(o []object.ID) *WorkflowExecutionCreate {
	wec.mutation.SetStageExecutionIds(o)
	return wec
}

// SetRecord sets the "record" field.
func (wec *WorkflowExecutionCreate) SetRecord(s string) *WorkflowExecutionCreate {
	wec.mutation.SetRecord(s)
	return wec
}

// SetNillableRecord sets the "record" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableRecord(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetRecord(*s)
	}
	return wec
}

// SetInput sets the "input" field.
func (wec *WorkflowExecutionCreate) SetInput(s string) *WorkflowExecutionCreate {
	wec.mutation.SetInput(s)
	return wec
}

// SetNillableInput sets the "input" field if the given value is not nil.
func (wec *WorkflowExecutionCreate) SetNillableInput(s *string) *WorkflowExecutionCreate {
	if s != nil {
		wec.SetInput(*s)
	}
	return wec
}

// SetID sets the "id" field.
func (wec *WorkflowExecutionCreate) SetID(o object.ID) *WorkflowExecutionCreate {
	wec.mutation.SetID(o)
	return wec
}

// SetProject sets the "project" edge to the Project entity.
func (wec *WorkflowExecutionCreate) SetProject(p *Project) *WorkflowExecutionCreate {
	return wec.SetProjectID(p.ID)
}

// AddWorkflowStageExecutionIDs adds the "workflow_stage_executions" edge to the WorkflowStageExecution entity by IDs.
func (wec *WorkflowExecutionCreate) AddWorkflowStageExecutionIDs(ids ...object.ID) *WorkflowExecutionCreate {
	wec.mutation.AddWorkflowStageExecutionIDs(ids...)
	return wec
}

// AddWorkflowStageExecutions adds the "workflow_stage_executions" edges to the WorkflowStageExecution entity.
func (wec *WorkflowExecutionCreate) AddWorkflowStageExecutions(w ...*WorkflowStageExecution) *WorkflowExecutionCreate {
	ids := make([]object.ID, len(w))
	for i := range w {
		ids[i] = w[i].ID
	}
	return wec.AddWorkflowStageExecutionIDs(ids...)
}

// SetWorkflow sets the "workflow" edge to the Workflow entity.
func (wec *WorkflowExecutionCreate) SetWorkflow(w *Workflow) *WorkflowExecutionCreate {
	return wec.SetWorkflowID(w.ID)
}

// Mutation returns the WorkflowExecutionMutation object of the builder.
func (wec *WorkflowExecutionCreate) Mutation() *WorkflowExecutionMutation {
	return wec.mutation
}

// Save creates the WorkflowExecution in the database.
func (wec *WorkflowExecutionCreate) Save(ctx context.Context) (*WorkflowExecution, error) {
	if err := wec.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, wec.sqlSave, wec.mutation, wec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wec *WorkflowExecutionCreate) SaveX(ctx context.Context) *WorkflowExecution {
	v, err := wec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wec *WorkflowExecutionCreate) Exec(ctx context.Context) error {
	_, err := wec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wec *WorkflowExecutionCreate) ExecX(ctx context.Context) {
	if err := wec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wec *WorkflowExecutionCreate) defaults() error {
	if _, ok := wec.mutation.Labels(); !ok {
		v := workflowexecution.DefaultLabels
		wec.mutation.SetLabels(v)
	}
	if _, ok := wec.mutation.Annotations(); !ok {
		v := workflowexecution.DefaultAnnotations
		wec.mutation.SetAnnotations(v)
	}
	if _, ok := wec.mutation.CreateTime(); !ok {
		if workflowexecution.DefaultCreateTime == nil {
			return fmt.Errorf("model: uninitialized workflowexecution.DefaultCreateTime (forgotten import model/runtime?)")
		}
		v := workflowexecution.DefaultCreateTime()
		wec.mutation.SetCreateTime(v)
	}
	if _, ok := wec.mutation.UpdateTime(); !ok {
		if workflowexecution.DefaultUpdateTime == nil {
			return fmt.Errorf("model: uninitialized workflowexecution.DefaultUpdateTime (forgotten import model/runtime?)")
		}
		v := workflowexecution.DefaultUpdateTime()
		wec.mutation.SetUpdateTime(v)
	}
	if _, ok := wec.mutation.Duration(); !ok {
		v := workflowexecution.DefaultDuration
		wec.mutation.SetDuration(v)
	}
	if _, ok := wec.mutation.StageExecutionIds(); !ok {
		v := workflowexecution.DefaultStageExecutionIds
		wec.mutation.SetStageExecutionIds(v)
	}
	if _, ok := wec.mutation.Record(); !ok {
		v := workflowexecution.DefaultRecord
		wec.mutation.SetRecord(v)
	}
	if _, ok := wec.mutation.Input(); !ok {
		v := workflowexecution.DefaultInput
		wec.mutation.SetInput(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (wec *WorkflowExecutionCreate) check() error {
	if _, ok := wec.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`model: missing required field "WorkflowExecution.name"`)}
	}
	if v, ok := wec.mutation.Name(); ok {
		if err := workflowexecution.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`model: validator failed for field "WorkflowExecution.name": %w`, err)}
		}
	}
	if _, ok := wec.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`model: missing required field "WorkflowExecution.create_time"`)}
	}
	if _, ok := wec.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`model: missing required field "WorkflowExecution.update_time"`)}
	}
	if _, ok := wec.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`model: missing required field "WorkflowExecution.project_id"`)}
	}
	if v, ok := wec.mutation.ProjectID(); ok {
		if err := workflowexecution.ProjectIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "project_id", err: fmt.Errorf(`model: validator failed for field "WorkflowExecution.project_id": %w`, err)}
		}
	}
	if _, ok := wec.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow_id", err: errors.New(`model: missing required field "WorkflowExecution.workflow_id"`)}
	}
	if v, ok := wec.mutation.WorkflowID(); ok {
		if err := workflowexecution.WorkflowIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "workflow_id", err: fmt.Errorf(`model: validator failed for field "WorkflowExecution.workflow_id": %w`, err)}
		}
	}
	if _, ok := wec.mutation.SubjectID(); !ok {
		return &ValidationError{Name: "subject_id", err: errors.New(`model: missing required field "WorkflowExecution.subject_id"`)}
	}
	if _, ok := wec.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`model: missing required field "WorkflowExecution.progress"`)}
	}
	if _, ok := wec.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`model: missing required field "WorkflowExecution.duration"`)}
	}
	if v, ok := wec.mutation.Duration(); ok {
		if err := workflowexecution.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`model: validator failed for field "WorkflowExecution.duration": %w`, err)}
		}
	}
	if _, ok := wec.mutation.StageExecutionIds(); !ok {
		return &ValidationError{Name: "stage_execution_ids", err: errors.New(`model: missing required field "WorkflowExecution.stage_execution_ids"`)}
	}
	if _, ok := wec.mutation.Record(); !ok {
		return &ValidationError{Name: "record", err: errors.New(`model: missing required field "WorkflowExecution.record"`)}
	}
	if _, ok := wec.mutation.Input(); !ok {
		return &ValidationError{Name: "input", err: errors.New(`model: missing required field "WorkflowExecution.input"`)}
	}
	if _, ok := wec.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project", err: errors.New(`model: missing required edge "WorkflowExecution.project"`)}
	}
	if _, ok := wec.mutation.WorkflowID(); !ok {
		return &ValidationError{Name: "workflow", err: errors.New(`model: missing required edge "WorkflowExecution.workflow"`)}
	}
	return nil
}

func (wec *WorkflowExecutionCreate) sqlSave(ctx context.Context) (*WorkflowExecution, error) {
	if err := wec.check(); err != nil {
		return nil, err
	}
	_node, _spec := wec.createSpec()
	if err := sqlgraph.CreateNode(ctx, wec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*object.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wec.mutation.id = &_node.ID
	wec.mutation.done = true
	return _node, nil
}

func (wec *WorkflowExecutionCreate) createSpec() (*WorkflowExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkflowExecution{config: wec.config}
		_spec = sqlgraph.NewCreateSpec(workflowexecution.Table, sqlgraph.NewFieldSpec(workflowexecution.FieldID, field.TypeString))
	)
	_spec.Schema = wec.schemaConfig.WorkflowExecution
	_spec.OnConflict = wec.conflict
	if id, ok := wec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wec.mutation.Name(); ok {
		_spec.SetField(workflowexecution.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := wec.mutation.Description(); ok {
		_spec.SetField(workflowexecution.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := wec.mutation.Labels(); ok {
		_spec.SetField(workflowexecution.FieldLabels, field.TypeJSON, value)
		_node.Labels = value
	}
	if value, ok := wec.mutation.Annotations(); ok {
		_spec.SetField(workflowexecution.FieldAnnotations, field.TypeJSON, value)
		_node.Annotations = value
	}
	if value, ok := wec.mutation.CreateTime(); ok {
		_spec.SetField(workflowexecution.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := wec.mutation.UpdateTime(); ok {
		_spec.SetField(workflowexecution.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := wec.mutation.Status(); ok {
		_spec.SetField(workflowexecution.FieldStatus, field.TypeJSON, value)
		_node.Status = value
	}
	if value, ok := wec.mutation.SubjectID(); ok {
		_spec.SetField(workflowexecution.FieldSubjectID, field.TypeString, value)
		_node.SubjectID = value
	}
	if value, ok := wec.mutation.Progress(); ok {
		_spec.SetField(workflowexecution.FieldProgress, field.TypeString, value)
		_node.Progress = value
	}
	if value, ok := wec.mutation.Duration(); ok {
		_spec.SetField(workflowexecution.FieldDuration, field.TypeInt, value)
		_node.Duration = value
	}
	if value, ok := wec.mutation.StageExecutionIds(); ok {
		_spec.SetField(workflowexecution.FieldStageExecutionIds, field.TypeJSON, value)
		_node.StageExecutionIds = value
	}
	if value, ok := wec.mutation.Record(); ok {
		_spec.SetField(workflowexecution.FieldRecord, field.TypeString, value)
		_node.Record = value
	}
	if value, ok := wec.mutation.Input(); ok {
		_spec.SetField(workflowexecution.FieldInput, field.TypeString, value)
		_node.Input = value
	}
	if nodes := wec.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowexecution.ProjectTable,
			Columns: []string{workflowexecution.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		edge.Schema = wec.schemaConfig.WorkflowExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := wec.mutation.WorkflowStageExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workflowexecution.WorkflowStageExecutionsTable,
			Columns: []string{workflowexecution.WorkflowStageExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflowstageexecution.FieldID, field.TypeString),
			},
		}
		edge.Schema = wec.schemaConfig.WorkflowStageExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := wec.mutation.WorkflowIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workflowexecution.WorkflowTable,
			Columns: []string{workflowexecution.WorkflowColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workflow.FieldID, field.TypeString),
			},
		}
		edge.Schema = wec.schemaConfig.WorkflowExecution
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkflowID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Set is different from other Set* methods,
// it sets the value by judging the definition of each field within the entire object.
//
// For required fields, Set calls directly.
//
// For optional fields, Set calls if the value is not zero.
//
// For example:
//
//	## Required
//
//	db.SetX(obj.X)
//
//	## Optional or Default
//
//	if _is_zero_value_(obj.X) {
//	   db.SetX(obj.X)
//	}
func (wec *WorkflowExecutionCreate) Set(obj *WorkflowExecution) *WorkflowExecutionCreate {
	// Required.
	wec.SetName(obj.Name)
	wec.SetProjectID(obj.ProjectID)
	wec.SetWorkflowID(obj.WorkflowID)
	wec.SetSubjectID(obj.SubjectID)
	wec.SetProgress(obj.Progress)
	wec.SetDuration(obj.Duration)
	wec.SetStageExecutionIds(obj.StageExecutionIds)
	wec.SetRecord(obj.Record)
	wec.SetInput(obj.Input)

	// Optional.
	if obj.Description != "" {
		wec.SetDescription(obj.Description)
	}
	if !reflect.ValueOf(obj.Labels).IsZero() {
		wec.SetLabels(obj.Labels)
	}
	if !reflect.ValueOf(obj.Annotations).IsZero() {
		wec.SetAnnotations(obj.Annotations)
	}
	if obj.CreateTime != nil {
		wec.SetCreateTime(*obj.CreateTime)
	}
	if obj.UpdateTime != nil {
		wec.SetUpdateTime(*obj.UpdateTime)
	}
	if !reflect.ValueOf(obj.Status).IsZero() {
		wec.SetStatus(obj.Status)
	}

	// Record the given object.
	wec.object = obj

	return wec
}

// getClientSet returns the ClientSet for the given builder.
func (wec *WorkflowExecutionCreate) getClientSet() (mc ClientSet) {
	if _, ok := wec.config.driver.(*txDriver); ok {
		tx := &Tx{config: wec.config}
		tx.init()
		mc = tx
	} else {
		cli := &Client{config: wec.config}
		cli.init()
		mc = cli
	}
	return mc
}

// SaveE calls the given function after created the WorkflowExecution entity,
// which is always good for cascading create operations.
func (wec *WorkflowExecutionCreate) SaveE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) (*WorkflowExecution, error) {
	obj, err := wec.Save(ctx)
	if err != nil {
		return nil, err
	}

	if len(cbs) == 0 {
		return obj, err
	}

	mc := wec.getClientSet()

	if x := wec.object; x != nil {
		if _, set := wec.mutation.Field(workflowexecution.FieldName); set {
			obj.Name = x.Name
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldDescription); set {
			obj.Description = x.Description
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldStatus); set {
			obj.Status = x.Status
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldProjectID); set {
			obj.ProjectID = x.ProjectID
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldWorkflowID); set {
			obj.WorkflowID = x.WorkflowID
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldSubjectID); set {
			obj.SubjectID = x.SubjectID
		}
		if _, set := wec.mutation.Field(workflowexecution.FieldProgress); set {
			obj.Progress = x.Progress
		}
		obj.Edges = x.Edges
	}

	for i := range cbs {
		if err = cbs[i](ctx, mc, obj); err != nil {
			return nil, err
		}
	}

	return obj, nil
}

// SaveEX is like SaveE, but panics if an error occurs.
func (wec *WorkflowExecutionCreate) SaveEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) *WorkflowExecution {
	obj, err := wec.SaveE(ctx, cbs...)
	if err != nil {
		panic(err)
	}
	return obj
}

// ExecE calls the given function after executed the query,
// which is always good for cascading create operations.
func (wec *WorkflowExecutionCreate) ExecE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) error {
	_, err := wec.SaveE(ctx, cbs...)
	return err
}

// ExecEX is like ExecE, but panics if an error occurs.
func (wec *WorkflowExecutionCreate) ExecEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) {
	if err := wec.ExecE(ctx, cbs...); err != nil {
		panic(err)
	}
}

// Set leverages the WorkflowExecutionCreate Set method,
// it sets the value by judging the definition of each field within the entire item of the given list.
//
// For required fields, Set calls directly.
//
// For optional fields, Set calls if the value is not zero.
//
// For example:
//
//	## Required
//
//	db.SetX(obj.X)
//
//	## Optional or Default
//
//	if _is_zero_value_(obj.X) {
//	   db.SetX(obj.X)
//	}
func (wecb *WorkflowExecutionCreateBulk) Set(objs ...*WorkflowExecution) *WorkflowExecutionCreateBulk {
	if len(objs) != 0 {
		client := NewWorkflowExecutionClient(wecb.config)

		wecb.builders = make([]*WorkflowExecutionCreate, len(objs))
		for i := range objs {
			wecb.builders[i] = client.Create().Set(objs[i])
		}

		// Record the given objects.
		wecb.objects = objs
	}

	return wecb
}

// getClientSet returns the ClientSet for the given builder.
func (wecb *WorkflowExecutionCreateBulk) getClientSet() (mc ClientSet) {
	if _, ok := wecb.config.driver.(*txDriver); ok {
		tx := &Tx{config: wecb.config}
		tx.init()
		mc = tx
	} else {
		cli := &Client{config: wecb.config}
		cli.init()
		mc = cli
	}
	return mc
}

// SaveE calls the given function after created the WorkflowExecution entities,
// which is always good for cascading create operations.
func (wecb *WorkflowExecutionCreateBulk) SaveE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) ([]*WorkflowExecution, error) {
	objs, err := wecb.Save(ctx)
	if err != nil {
		return nil, err
	}

	if len(cbs) == 0 {
		return objs, err
	}

	mc := wecb.getClientSet()

	if x := wecb.objects; x != nil {
		for i := range x {
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldName); set {
				objs[i].Name = x[i].Name
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldDescription); set {
				objs[i].Description = x[i].Description
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldStatus); set {
				objs[i].Status = x[i].Status
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldProjectID); set {
				objs[i].ProjectID = x[i].ProjectID
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldWorkflowID); set {
				objs[i].WorkflowID = x[i].WorkflowID
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldSubjectID); set {
				objs[i].SubjectID = x[i].SubjectID
			}
			if _, set := wecb.builders[i].mutation.Field(workflowexecution.FieldProgress); set {
				objs[i].Progress = x[i].Progress
			}
			objs[i].Edges = x[i].Edges
		}
	}

	for i := range objs {
		for j := range cbs {
			if err = cbs[j](ctx, mc, objs[i]); err != nil {
				return nil, err
			}
		}
	}

	return objs, nil
}

// SaveEX is like SaveE, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) SaveEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) []*WorkflowExecution {
	objs, err := wecb.SaveE(ctx, cbs...)
	if err != nil {
		panic(err)
	}
	return objs
}

// ExecE calls the given function after executed the query,
// which is always good for cascading create operations.
func (wecb *WorkflowExecutionCreateBulk) ExecE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) error {
	_, err := wecb.SaveE(ctx, cbs...)
	return err
}

// ExecEX is like ExecE, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) ExecEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, created *WorkflowExecution) error) {
	if err := wecb.ExecE(ctx, cbs...); err != nil {
		panic(err)
	}
}

// ExecE calls the given function after executed the query,
// which is always good for cascading create operations.
func (u *WorkflowExecutionUpsertOne) ExecE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowExecution) error) error {
	if len(u.create.conflict) == 0 {
		return errors.New("model: missing options for WorkflowExecutionUpsertOne.OnConflict")
	}
	u.create.fromUpsert = true
	return u.create.ExecE(ctx, cbs...)
}

// ExecEX is like ExecE, but panics if an error occurs.
func (u *WorkflowExecutionUpsertOne) ExecEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowExecution) error) {
	if err := u.ExecE(ctx, cbs...); err != nil {
		panic(err)
	}
}

// ExecE calls the given function after executed the query,
// which is always good for cascading create operations.
func (u *WorkflowExecutionUpsertBulk) ExecE(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowExecution) error) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("model: OnConflict was set for builder %d. Set it on the WorkflowExecutionUpsertBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("model: missing options for WorkflowExecutionUpsertBulk.OnConflict")
	}
	u.create.fromUpsert = true
	return u.create.ExecE(ctx, cbs...)
}

// ExecEX is like ExecE, but panics if an error occurs.
func (u *WorkflowExecutionUpsertBulk) ExecEX(ctx context.Context, cbs ...func(ctx context.Context, mc ClientSet, updated *WorkflowExecution) error) {
	if err := u.ExecE(ctx, cbs...); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkflowExecution.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkflowExecutionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (wec *WorkflowExecutionCreate) OnConflict(opts ...sql.ConflictOption) *WorkflowExecutionUpsertOne {
	wec.conflict = opts
	return &WorkflowExecutionUpsertOne{
		create: wec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wec *WorkflowExecutionCreate) OnConflictColumns(columns ...string) *WorkflowExecutionUpsertOne {
	wec.conflict = append(wec.conflict, sql.ConflictColumns(columns...))
	return &WorkflowExecutionUpsertOne{
		create: wec,
	}
}

type (
	// WorkflowExecutionUpsertOne is the builder for "upsert"-ing
	//  one WorkflowExecution node.
	WorkflowExecutionUpsertOne struct {
		create *WorkflowExecutionCreate
	}

	// WorkflowExecutionUpsert is the "OnConflict" setter.
	WorkflowExecutionUpsert struct {
		*sql.UpdateSet
	}
)

// SetDescription sets the "description" field.
func (u *WorkflowExecutionUpsert) SetDescription(v string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateDescription() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *WorkflowExecutionUpsert) ClearDescription() *WorkflowExecutionUpsert {
	u.SetNull(workflowexecution.FieldDescription)
	return u
}

// SetLabels sets the "labels" field.
func (u *WorkflowExecutionUpsert) SetLabels(v map[string]string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldLabels, v)
	return u
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateLabels() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldLabels)
	return u
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkflowExecutionUpsert) ClearLabels() *WorkflowExecutionUpsert {
	u.SetNull(workflowexecution.FieldLabels)
	return u
}

// SetAnnotations sets the "annotations" field.
func (u *WorkflowExecutionUpsert) SetAnnotations(v map[string]string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldAnnotations, v)
	return u
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateAnnotations() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldAnnotations)
	return u
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *WorkflowExecutionUpsert) ClearAnnotations() *WorkflowExecutionUpsert {
	u.SetNull(workflowexecution.FieldAnnotations)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *WorkflowExecutionUpsert) SetUpdateTime(v time.Time) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateUpdateTime() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldUpdateTime)
	return u
}

// SetStatus sets the "status" field.
func (u *WorkflowExecutionUpsert) SetStatus(v status.Status) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateStatus() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldStatus)
	return u
}

// ClearStatus clears the value of the "status" field.
func (u *WorkflowExecutionUpsert) ClearStatus() *WorkflowExecutionUpsert {
	u.SetNull(workflowexecution.FieldStatus)
	return u
}

// SetProgress sets the "progress" field.
func (u *WorkflowExecutionUpsert) SetProgress(v string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldProgress, v)
	return u
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateProgress() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldProgress)
	return u
}

// SetDuration sets the "duration" field.
func (u *WorkflowExecutionUpsert) SetDuration(v int) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldDuration, v)
	return u
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateDuration() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldDuration)
	return u
}

// AddDuration adds v to the "duration" field.
func (u *WorkflowExecutionUpsert) AddDuration(v int) *WorkflowExecutionUpsert {
	u.Add(workflowexecution.FieldDuration, v)
	return u
}

// SetStageExecutionIds sets the "stage_execution_ids" field.
func (u *WorkflowExecutionUpsert) SetStageExecutionIds(v []object.ID) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldStageExecutionIds, v)
	return u
}

// UpdateStageExecutionIds sets the "stage_execution_ids" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateStageExecutionIds() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldStageExecutionIds)
	return u
}

// SetRecord sets the "record" field.
func (u *WorkflowExecutionUpsert) SetRecord(v string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldRecord, v)
	return u
}

// UpdateRecord sets the "record" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateRecord() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldRecord)
	return u
}

// SetInput sets the "input" field.
func (u *WorkflowExecutionUpsert) SetInput(v string) *WorkflowExecutionUpsert {
	u.Set(workflowexecution.FieldInput, v)
	return u
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *WorkflowExecutionUpsert) UpdateInput() *WorkflowExecutionUpsert {
	u.SetExcluded(workflowexecution.FieldInput)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workflowexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkflowExecutionUpsertOne) UpdateNewValues() *WorkflowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(workflowexecution.FieldID)
		}
		if _, exists := u.create.mutation.Name(); exists {
			s.SetIgnore(workflowexecution.FieldName)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(workflowexecution.FieldCreateTime)
		}
		if _, exists := u.create.mutation.ProjectID(); exists {
			s.SetIgnore(workflowexecution.FieldProjectID)
		}
		if _, exists := u.create.mutation.WorkflowID(); exists {
			s.SetIgnore(workflowexecution.FieldWorkflowID)
		}
		if _, exists := u.create.mutation.SubjectID(); exists {
			s.SetIgnore(workflowexecution.FieldSubjectID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *WorkflowExecutionUpsertOne) Ignore() *WorkflowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkflowExecutionUpsertOne) DoNothing() *WorkflowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkflowExecutionCreate.OnConflict
// documentation for more info.
func (u *WorkflowExecutionUpsertOne) Update(set func(*WorkflowExecutionUpsert)) *WorkflowExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkflowExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDescription sets the "description" field.
func (u *WorkflowExecutionUpsertOne) SetDescription(v string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateDescription() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *WorkflowExecutionUpsertOne) ClearDescription() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearDescription()
	})
}

// SetLabels sets the "labels" field.
func (u *WorkflowExecutionUpsertOne) SetLabels(v map[string]string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateLabels() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateLabels()
	})
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkflowExecutionUpsertOne) ClearLabels() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearLabels()
	})
}

// SetAnnotations sets the "annotations" field.
func (u *WorkflowExecutionUpsertOne) SetAnnotations(v map[string]string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetAnnotations(v)
	})
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateAnnotations() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateAnnotations()
	})
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *WorkflowExecutionUpsertOne) ClearAnnotations() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearAnnotations()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *WorkflowExecutionUpsertOne) SetUpdateTime(v time.Time) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateUpdateTime() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *WorkflowExecutionUpsertOne) SetStatus(v status.Status) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateStatus() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *WorkflowExecutionUpsertOne) ClearStatus() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *WorkflowExecutionUpsertOne) SetProgress(v string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateProgress() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateProgress()
	})
}

// SetDuration sets the "duration" field.
func (u *WorkflowExecutionUpsertOne) SetDuration(v int) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetDuration(v)
	})
}

// AddDuration adds v to the "duration" field.
func (u *WorkflowExecutionUpsertOne) AddDuration(v int) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.AddDuration(v)
	})
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateDuration() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateDuration()
	})
}

// SetStageExecutionIds sets the "stage_execution_ids" field.
func (u *WorkflowExecutionUpsertOne) SetStageExecutionIds(v []object.ID) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetStageExecutionIds(v)
	})
}

// UpdateStageExecutionIds sets the "stage_execution_ids" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateStageExecutionIds() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateStageExecutionIds()
	})
}

// SetRecord sets the "record" field.
func (u *WorkflowExecutionUpsertOne) SetRecord(v string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetRecord(v)
	})
}

// UpdateRecord sets the "record" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateRecord() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateRecord()
	})
}

// SetInput sets the "input" field.
func (u *WorkflowExecutionUpsertOne) SetInput(v string) *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertOne) UpdateInput() *WorkflowExecutionUpsertOne {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateInput()
	})
}

// Exec executes the query.
func (u *WorkflowExecutionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("model: missing options for WorkflowExecutionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkflowExecutionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *WorkflowExecutionUpsertOne) ID(ctx context.Context) (id object.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("model: WorkflowExecutionUpsertOne.ID is not supported by MySQL driver. Use WorkflowExecutionUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *WorkflowExecutionUpsertOne) IDX(ctx context.Context) object.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// WorkflowExecutionCreateBulk is the builder for creating many WorkflowExecution entities in bulk.
type WorkflowExecutionCreateBulk struct {
	config
	builders   []*WorkflowExecutionCreate
	conflict   []sql.ConflictOption
	objects    []*WorkflowExecution
	fromUpsert bool
}

// Save creates the WorkflowExecution entities in the database.
func (wecb *WorkflowExecutionCreateBulk) Save(ctx context.Context) ([]*WorkflowExecution, error) {
	specs := make([]*sqlgraph.CreateSpec, len(wecb.builders))
	nodes := make([]*WorkflowExecution, len(wecb.builders))
	mutators := make([]Mutator, len(wecb.builders))
	for i := range wecb.builders {
		func(i int, root context.Context) {
			builder := wecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkflowExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = wecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) SaveX(ctx context.Context) []*WorkflowExecution {
	v, err := wecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wecb *WorkflowExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := wecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wecb *WorkflowExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := wecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.WorkflowExecution.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.WorkflowExecutionUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (wecb *WorkflowExecutionCreateBulk) OnConflict(opts ...sql.ConflictOption) *WorkflowExecutionUpsertBulk {
	wecb.conflict = opts
	return &WorkflowExecutionUpsertBulk{
		create: wecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (wecb *WorkflowExecutionCreateBulk) OnConflictColumns(columns ...string) *WorkflowExecutionUpsertBulk {
	wecb.conflict = append(wecb.conflict, sql.ConflictColumns(columns...))
	return &WorkflowExecutionUpsertBulk{
		create: wecb,
	}
}

// WorkflowExecutionUpsertBulk is the builder for "upsert"-ing
// a bulk of WorkflowExecution nodes.
type WorkflowExecutionUpsertBulk struct {
	create *WorkflowExecutionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(workflowexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *WorkflowExecutionUpsertBulk) UpdateNewValues() *WorkflowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(workflowexecution.FieldID)
			}
			if _, exists := b.mutation.Name(); exists {
				s.SetIgnore(workflowexecution.FieldName)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(workflowexecution.FieldCreateTime)
			}
			if _, exists := b.mutation.ProjectID(); exists {
				s.SetIgnore(workflowexecution.FieldProjectID)
			}
			if _, exists := b.mutation.WorkflowID(); exists {
				s.SetIgnore(workflowexecution.FieldWorkflowID)
			}
			if _, exists := b.mutation.SubjectID(); exists {
				s.SetIgnore(workflowexecution.FieldSubjectID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.WorkflowExecution.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *WorkflowExecutionUpsertBulk) Ignore() *WorkflowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *WorkflowExecutionUpsertBulk) DoNothing() *WorkflowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the WorkflowExecutionCreateBulk.OnConflict
// documentation for more info.
func (u *WorkflowExecutionUpsertBulk) Update(set func(*WorkflowExecutionUpsert)) *WorkflowExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&WorkflowExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetDescription sets the "description" field.
func (u *WorkflowExecutionUpsertBulk) SetDescription(v string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateDescription() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *WorkflowExecutionUpsertBulk) ClearDescription() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearDescription()
	})
}

// SetLabels sets the "labels" field.
func (u *WorkflowExecutionUpsertBulk) SetLabels(v map[string]string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetLabels(v)
	})
}

// UpdateLabels sets the "labels" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateLabels() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateLabels()
	})
}

// ClearLabels clears the value of the "labels" field.
func (u *WorkflowExecutionUpsertBulk) ClearLabels() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearLabels()
	})
}

// SetAnnotations sets the "annotations" field.
func (u *WorkflowExecutionUpsertBulk) SetAnnotations(v map[string]string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetAnnotations(v)
	})
}

// UpdateAnnotations sets the "annotations" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateAnnotations() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateAnnotations()
	})
}

// ClearAnnotations clears the value of the "annotations" field.
func (u *WorkflowExecutionUpsertBulk) ClearAnnotations() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearAnnotations()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *WorkflowExecutionUpsertBulk) SetUpdateTime(v time.Time) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateUpdateTime() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateUpdateTime()
	})
}

// SetStatus sets the "status" field.
func (u *WorkflowExecutionUpsertBulk) SetStatus(v status.Status) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateStatus() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateStatus()
	})
}

// ClearStatus clears the value of the "status" field.
func (u *WorkflowExecutionUpsertBulk) ClearStatus() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.ClearStatus()
	})
}

// SetProgress sets the "progress" field.
func (u *WorkflowExecutionUpsertBulk) SetProgress(v string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetProgress(v)
	})
}

// UpdateProgress sets the "progress" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateProgress() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateProgress()
	})
}

// SetDuration sets the "duration" field.
func (u *WorkflowExecutionUpsertBulk) SetDuration(v int) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetDuration(v)
	})
}

// AddDuration adds v to the "duration" field.
func (u *WorkflowExecutionUpsertBulk) AddDuration(v int) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.AddDuration(v)
	})
}

// UpdateDuration sets the "duration" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateDuration() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateDuration()
	})
}

// SetStageExecutionIds sets the "stage_execution_ids" field.
func (u *WorkflowExecutionUpsertBulk) SetStageExecutionIds(v []object.ID) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetStageExecutionIds(v)
	})
}

// UpdateStageExecutionIds sets the "stage_execution_ids" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateStageExecutionIds() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateStageExecutionIds()
	})
}

// SetRecord sets the "record" field.
func (u *WorkflowExecutionUpsertBulk) SetRecord(v string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetRecord(v)
	})
}

// UpdateRecord sets the "record" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateRecord() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateRecord()
	})
}

// SetInput sets the "input" field.
func (u *WorkflowExecutionUpsertBulk) SetInput(v string) *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.SetInput(v)
	})
}

// UpdateInput sets the "input" field to the value that was provided on create.
func (u *WorkflowExecutionUpsertBulk) UpdateInput() *WorkflowExecutionUpsertBulk {
	return u.Update(func(s *WorkflowExecutionUpsert) {
		s.UpdateInput()
	})
}

// Exec executes the query.
func (u *WorkflowExecutionUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("model: OnConflict was set for builder %d. Set it on the WorkflowExecutionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("model: missing options for WorkflowExecutionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *WorkflowExecutionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
