# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
metadata:
  generateName: http-template-
kind: Workflow
spec:
  entrypoint: entrypoint
  templates:
  - name: entrypoint
    steps:
      - - name: echo
          template: echo
      - - name: my-step
          template: my-step
  - name: echo
    metadata:
      labels:
        app: echo
    container:
      image: ubuntu
      command: [echo]
      args: ["hello world, 12312321"]
  - name: my-step
    metadata:
      labels:
        app: my-app
        env: production
    container:
      image: ubuntu
      command: [sh, -c]
      args: ["apt-get update -y && apt-get install -y iputils-ping && ping www.baidu.com"]
