// SPDX-FileCopyrightText: 2023 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus". DO NOT EDIT.

package workflowstageexecution

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"golang.org/x/exp/slices"

	"github.com/seal-io/walrus/pkg/dao/types/object"
)

const (
	// Label holds the string label denoting the workflowstageexecution type in the database.
	Label = "workflow_stage_execution"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLabels holds the string denoting the labels field in the database.
	FieldLabels = "labels"
	// FieldAnnotations holds the string denoting the annotations field in the database.
	FieldAnnotations = "annotations"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// FieldStageID holds the string denoting the stage_id field in the database.
	FieldStageID = "stage_id"
	// FieldWorkflowExecutionID holds the string denoting the workflow_execution_id field in the database.
	FieldWorkflowExecutionID = "workflow_execution_id"
	// FieldStepExecutionIds holds the string denoting the step_execution_ids field in the database.
	FieldStepExecutionIds = "step_execution_ids"
	// FieldRecord holds the string denoting the record field in the database.
	FieldRecord = "record"
	// FieldInput holds the string denoting the input field in the database.
	FieldInput = "input"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeStepExecutions holds the string denoting the step_executions edge name in mutations.
	EdgeStepExecutions = "step_executions"
	// EdgeStage holds the string denoting the stage edge name in mutations.
	EdgeStage = "stage"
	// EdgeExecution holds the string denoting the execution edge name in mutations.
	EdgeExecution = "execution"
	// Table holds the table name of the workflowstageexecution in the database.
	Table = "workflow_stage_executions"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "workflow_stage_executions"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// StepExecutionsTable is the table that holds the step_executions relation/edge.
	StepExecutionsTable = "workflow_step_executions"
	// StepExecutionsInverseTable is the table name for the WorkflowStepExecution entity.
	// It exists in this package in order to avoid circular dependency with the "workflowstepexecution" package.
	StepExecutionsInverseTable = "workflow_step_executions"
	// StepExecutionsColumn is the table column denoting the step_executions relation/edge.
	StepExecutionsColumn = "workflow_stage_execution_id"
	// StageTable is the table that holds the stage relation/edge.
	StageTable = "workflow_stage_executions"
	// StageInverseTable is the table name for the WorkflowStage entity.
	// It exists in this package in order to avoid circular dependency with the "workflowstage" package.
	StageInverseTable = "workflow_stages"
	// StageColumn is the table column denoting the stage relation/edge.
	StageColumn = "stage_id"
	// ExecutionTable is the table that holds the execution relation/edge.
	ExecutionTable = "workflow_stage_executions"
	// ExecutionInverseTable is the table name for the WorkflowExecution entity.
	// It exists in this package in order to avoid circular dependency with the "workflowexecution" package.
	ExecutionInverseTable = "workflow_executions"
	// ExecutionColumn is the table column denoting the execution relation/edge.
	ExecutionColumn = "workflow_execution_id"
)

// Columns holds all SQL columns for workflowstageexecution fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldLabels,
	FieldAnnotations,
	FieldCreateTime,
	FieldUpdateTime,
	FieldStatus,
	FieldProjectID,
	FieldDuration,
	FieldStageID,
	FieldWorkflowExecutionID,
	FieldStepExecutionIds,
	FieldRecord,
	FieldInput,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/seal-io/walrus/pkg/dao/model/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLabels holds the default value on creation for the "labels" field.
	DefaultLabels map[string]string
	// DefaultAnnotations holds the default value on creation for the "annotations" field.
	DefaultAnnotations map[string]string
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// ProjectIDValidator is a validator for the "project_id" field. It is called by the builders before save.
	ProjectIDValidator func(string) error
	// DefaultDuration holds the default value on creation for the "duration" field.
	DefaultDuration int
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(int) error
	// DefaultStepExecutionIds holds the default value on creation for the "step_execution_ids" field.
	DefaultStepExecutionIds []object.ID
	// DefaultRecord holds the default value on creation for the "record" field.
	DefaultRecord string
	// DefaultInput holds the default value on creation for the "input" field.
	DefaultInput string
)

// OrderOption defines the ordering options for the WorkflowStageExecution queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}

// ByStageID orders the results by the stage_id field.
func ByStageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStageID, opts...).ToFunc()
}

// ByWorkflowExecutionID orders the results by the workflow_execution_id field.
func ByWorkflowExecutionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkflowExecutionID, opts...).ToFunc()
}

// ByRecord orders the results by the record field.
func ByRecord(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecord, opts...).ToFunc()
}

// ByInput orders the results by the input field.
func ByInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInput, opts...).ToFunc()
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByStepExecutionsCount orders the results by step_executions count.
func ByStepExecutionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStepExecutionsStep(), opts...)
	}
}

// ByStepExecutions orders the results by step_executions terms.
func ByStepExecutions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStepExecutionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByStageField orders the results by stage field.
func ByStageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStageStep(), sql.OrderByField(field, opts...))
	}
}

// ByExecutionField orders the results by execution field.
func ByExecutionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExecutionStep(), sql.OrderByField(field, opts...))
	}
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newStepExecutionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StepExecutionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, StepExecutionsTable, StepExecutionsColumn),
	)
}
func newStageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StageTable, StageColumn),
	)
}
func newExecutionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExecutionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ExecutionTable, ExecutionColumn),
	)
}

// WithoutFields returns the fields ignored the given list.
func WithoutFields(ignores ...string) []string {
	if len(ignores) == 0 {
		return slices.Clone(Columns)
	}

	var s = make(map[string]bool, len(ignores))
	for i := range ignores {
		s[ignores[i]] = true
	}

	var r = make([]string, 0, len(Columns)-len(s))
	for i := range Columns {
		if s[Columns[i]] {
			continue
		}
		r = append(r, Columns[i])
	}
	return r
}
